### ISSUE TITLE
DOC: improved readme

### ISSUE THREAD

**Issue by tannuiscoding** [tannuiscoding/GoEco#1]
I want this readme file to have these following features 

- short description of project 
- tech stack of the project
- steps to setup the project

**Comment by prashant4833o** [comment]
I can finish this before Diwali.

**Comment by kartik-212004** [comment]
I would like to resolve this issue. Please assign it to me.
Thanks

**Comment by RishiAnand108** [comment]
PLEASE ASSIGN ME I CAN HELP

**Comment by HarshL14** [comment]
PLEASE ASSIGN ME FOR THIS PROJECT

**Comment by bdhamithkumara** [comment]
I don't think this will take a long time to fix. If it is not completed by today, can you @tannuiscoding  please assign it to me?

**Comment by tannuiscoding** [comment]
> I don't think this will take a long time to fix. If it is not completed by today, can you @tannuiscoding please assign it to me?

It'll be really nice if You can improve the readme in [cut-it-short](https://GitHub.com/tannuiscoding/cut-it-short)

**Comment by RishiAnand108** [comment]
i have made a pr please accept it
.

**Comment by bdhamithkumara** [comment]
> > I don't think this will take a long time to fix. If it is not completed by today, can you @tannuiscoding please assign it to me?
> 
> It'll be really nice if You can improve the readme in [cut-it-short](https://GitHub.com/tannuiscoding/cut-it-short)

sure 💪
