### ISSUE TITLE
wrong instructions in README.MD

### ISSUE THREAD

**Issue by bdhamithkumara** [tannuiscoding/GoEco#11]
we need to use weatherAPI for this not a Hugging Face 

current README.MD 

![image](https://github.com/user-attachments/assets/de04273c-90e8-469e-afa3-ee8441735e90)

in app.py

![image](https://github.com/user-attachments/assets/98031c07-f70c-435a-93a7-cdf9d36df49e)

**Comment by tannuiscoding** [comment]
Thanks for pointing out. You're assigned.
