### ISSUE TITLE
Enhancements: better UI of work page

### ISSUE THREAD

**Issue by tannuiscoding** [tannuiscoding/GoEco#2]
Currently the work page has different company names and list in a nested division,
I want them to be in different div/containers similar to team page.

**Comment by prashant4833o** [comment]
Ok then I will asap

**Comment by RishiAnand108** [comment]
PLEASE ASSIGNME I  CAN HELP YOU DOING THESE

**Comment by Snxdxp4** [comment]
i made a pr request for this issue check it out

**Comment by tannuiscoding** [comment]
> i made a pr request for this issue check it out

Thank you so much for your contribution. It is not merged. I will close this issue as completed.
