### ISSUE TITLE
Create a new CONTRIBUTING.md file and adding a How to Contribute section in it.

### ISSUE THREAD

**Issue by Snehshishdutta** [tannuiscoding/GoEco#3]
Suggestion to Add a CONTRIBUTING.md file.

I think a "How to Contribute" section in the CONTRIBUTING.md file would be a great addition. This section could provide new contributors with a clear guide on how to get involved, including steps like:

1.Setting up the project locally
2.Finding good first issues
3.Coding standards or style guidelines
4.Creating pull requests

Adding these details could make it easier for new contributors to get started and increase overall contributions to the project. Can u assign this issue to me under hacktoberfest label?

**Comment by tannuiscoding** [comment]
@Snehshishdutta you're assigned

**Comment by Snehshishdutta** [comment]
> @Snehshishdutta you're assigned

Thank you
