### ISSUE TITLE
New Feature: Cost-Benefit Analysis Tool

### ISSUE THREAD

**Issue by pokymono** [tannuiscoding/GoEco#4]
Developing a calculator that compares the costs and benefits of different renewable energy options (installation, maintenance, savings over time).
please assign me this under hacktoberfest label :)

**Comment by Snxdxp4** [comment]
can you assign this to me

**Comment by tannuiscoding** [comment]
> can you assign this to me

This issue was assigned to @Rishitshivam 9 hours ago, if there would be no progress until tomorrow morning, I will assign it to you. Thank you.

**Comment by tannuiscoding** [comment]
@Snxdxp4 you are assigned for this issue. Thank you.

**Comment by Snxdxp4** [comment]
i'm on it

**Comment by pokymono** [comment]
Hey! sorry I was busy due to diwali, tag me  if you want me to work on this.

**Comment by tannuiscoding** [comment]
> Hey! sorry I was busy due to diwali, tag me if you want me to work on this.

Thank you so much for taking interest in this project. I appreciate your time and effort. This issue is being closed, as the feature has been added. 
Please look for other issues if you'd like to contribute.
